{"uuid": "9594a518-3ecd-4c4e-9e6b-9bb6328df561", "children": ["e37eb638-8cd5-4fd0-b3d6-66da2ae49d26"], "befores": [{"name": "selenium", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10ff3dbd0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "trace": "  File \"/Users/galinashaydurova/miniconda/envs/skillbox_22/lib/python3.11/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/galinashaydurova/miniconda/envs/skillbox_22/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1130, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/galinashaydurova/miniconda/envs/skillbox_22/lib/python3.11/site-packages/_pytest/fixtures.py\", line 902, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/Users/galinashaydurova/PycharmProjects/python-autotests-basic/module_6/src/fixtures/system/browser.py\", line 14, in selenium\n    driver = Remote(\n             ^^^^^^^\n  File \"/Users/galinashaydurova/miniconda/envs/skillbox_22/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 286, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"/Users/galinashaydurova/miniconda/envs/skillbox_22/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 378, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/galinashaydurova/miniconda/envs/skillbox_22/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 438, in execute\n    response = self.command_executor.execute(driver_command, params)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/galinashaydurova/miniconda/envs/skillbox_22/lib/python3.11/site-packages/selenium/webdriver/remote/remote_connection.py\", line 290, in execute\n    return self._request(command_info[0], url, body=data)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/galinashaydurova/miniconda/envs/skillbox_22/lib/python3.11/site-packages/selenium/webdriver/remote/remote_connection.py\", line 311, in _request\n    response = self._conn.request(method, url, body=body, headers=headers)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/galinashaydurova/miniconda/envs/skillbox_22/lib/python3.11/site-packages/urllib3/request.py\", line 78, in request\n    return self.request_encode_body(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/galinashaydurova/miniconda/envs/skillbox_22/lib/python3.11/site-packages/urllib3/request.py\", line 170, in request_encode_body\n    return self.urlopen(method, url, **extra_kw)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/galinashaydurova/miniconda/envs/skillbox_22/lib/python3.11/site-packages/urllib3/poolmanager.py\", line 376, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/galinashaydurova/miniconda/envs/skillbox_22/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 815, in urlopen\n    return self.urlopen(\n           ^^^^^^^^^^^^^\n  File \"/Users/galinashaydurova/miniconda/envs/skillbox_22/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 815, in urlopen\n    return self.urlopen(\n           ^^^^^^^^^^^^^\n  File \"/Users/galinashaydurova/miniconda/envs/skillbox_22/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 815, in urlopen\n    return self.urlopen(\n           ^^^^^^^^^^^^^\n  File \"/Users/galinashaydurova/miniconda/envs/skillbox_22/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 787, in urlopen\n    retries = retries.increment(\n              ^^^^^^^^^^^^^^^^^^\n  File \"/Users/galinashaydurova/miniconda/envs/skillbox_22/lib/python3.11/site-packages/urllib3/util/retry.py\", line 592, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\n"}, "start": 1684427256284, "stop": 1684427256294}], "start": 1684427256284, "stop": 1684427256625}